### PR TITLE
checking pull request

### PR DESCRIPTION
**Pull request by yashaswini-101296**

### CODE REVIEW

**Comment by yashaswini-101296** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign 
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=Yashaswini-yashas%2Fps-jx-test-import).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/Yashaswini-yashas/ps-jx-test-import/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by Yashaswini-yashas** [comment]
i like cats

/meow

**Comment by yashaswini-101296** [comment]
@Yashaswini-yashas: cat image

<details>

In response to [this](https://github.com/Yashaswini-yashas/ps-jx-test-import/pull/1#issuecomment-716386935):

>i like cats
>
>/meow


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository.
</details>

**Comment by Yashaswini-yashas** [comment]
i like dogs

/dogs

**Comment by Yashaswini-yashas** [comment]
i like dogs

/bow

**Comment by Yashaswini-yashas** [comment]
Great change

/lgtm

**Comment by yashaswini-101296** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *[Yashaswini-yashas](https://github.com/Yashaswini-yashas/ps-jx-test-import/pull/1#issuecomment-716387976 "LGTM")*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign 
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=Yashaswini-yashas%2Fps-jx-test-import).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/Yashaswini-yashas/ps-jx-test-import/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by yashaswini-101296** [comment]
@yashaswini-101296: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | 7d728abcc9d89563cbbc9febcf59ddfb3d7cb807 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Pull request merged**
